it:
  fra:
    test:
      proxy:
        TvSeriesProxy/mp-rest/uri: https://api.tvmaze.com
        TvSeriesProxy/mp-rest/scope: javax.inject.Singleton
        TvEpisodesProxy/mp-rest/uri: https://api.tvmaze.com
        TvEpisodesProxy/mp-rest/scope: javax.inject.Singleton

quarkus:
  http:
    cors:
      ~: true
      origins: "*"
      methods: GET, POST, PUT, DELETE
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
      access-control-allow-credentials: true

      